import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const Terms = () => {
  return (
    <motion.main
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-black min-h-screen text-primary"
    >
      <div className="max-w-4xl mx-auto px-6 py-24 md:py-32">
        {/* Task 1: Back Navigation */}
        <div className="mb-16">
          <Link 
            to="/" 
            className="font-mono text-xs tracking-[0.3em] text-primary/40 hover:text-secondary transition-colors uppercase"
          >
            [ RETURN_TO_SYSTEM ]
          </Link>
        </div>

        {/* Task 2: Header Section */}
        <header className="mb-12">
          <span className="font-mono text-[10px] text-secondary tracking-[0.4em] uppercase">// OPERATING_DIRECTIVES_V1.0</span>
          <h1 className="font-serif text-5xl md:text-7xl italic text-primary mt-4 mb-8">Terms of Service.</h1>
          
          <div className="border border-[#222222] p-6 rounded-lg bg-[#050505] shadow-2xl">
            <p className="font-mono text-[11px] text-primary/60 leading-relaxed uppercase tracking-wider">
              "By initiating a handshake through our contact portal, you agree to the following system-wide directives."
            </p>
          </div>
        </header>

        {/* Task 3: Content Injection */}
        <div className="space-y-12 font-sans text-lg text-primary/80 leading-relaxed">
          
          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">1. Scope of Architecture</h2>
            <p>
              Prisma Digital provides custom web design, UI/UX architecture, and AI integration services. All projects are bound by a specific "Statement of Work." Features requested outside of the initial agreed-upon payload are considered "Scope Creep" and will require a separate transmission and billing audit.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">2. The Milestone Payment Protocol</h2>
            <p className="mb-6">To ensure project velocity and security, we operate on a milestone basis:</p>
            <ul className="list-disc pl-6 space-y-4">
              <li><strong>Commencement:</strong> A 50% non-refundable deposit is required to initialize the project nodes.</li>
              <li><strong>Finalization:</strong> The remaining 50% must be settled before the final handover of assets or deployment to the client's live domain.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">3. International & Domestic Settlement</h2>
            <div className="space-y-6">
              <p><strong>India (Domestic):</strong> Payments via UPI or NEFT are verified instantly.</p>
              <p><strong>International (Global):</strong> For clients outside India, we utilize SWIFT, Stripe, or PayPal. Note: Work on subsequent phases only resumes once funds are cleared in our local accounts (typically 3–7 business days). We do not accept "payment screenshots" as verification of funds.</p>
            </div>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">4. Ownership & Intellectual Property</h2>
            <p className="p-6 bg-secondary/5 border border-secondary/20 rounded-lg italic">
              Critical Directive: All code, custom animations, and UI designs remain the legal property of Prisma Digital until the final invoice is paid in full. Upon 100% settlement, the architectural license and ownership are transferred to the client. We reserve the right to remove un-paid sites from our servers.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">5. The "Kill Fee" & Refund Policy</h2>
            <p>
              Once the digital architecture has begun, the 50% commencement deposit is non-refundable. If a project is cancelled by the client during development, a "Kill Fee" proportional to the hours worked will be applied.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">6. AI Reliability Disclaimer</h2>
            <p>
              For projects involving local LLMs (Gemma 4 E2b, etc.), the client acknowledges that AI outputs are probabilistic. Prisma Digital is not liable for data generated by AI models; all technical outputs should be verified by the client before public deployment.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">7. Limitation of Liability</h2>
            <p>
              Prisma Digital is not responsible for any server downtime, loss of data, or business interruption caused by third-party hosting providers or the client’s internal hardware failures.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-primary mb-6">8. Node Jurisdiction</h2>
            <p>
              These directives are governed by the laws of Gujarat, India. Any disputes must be resolved within this primary node's jurisdiction.
            </p>
          </section>

        </div>
      </div>
    </motion.main>
  );
};

export default Terms;
